apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: db-runbooks
build:
  artifacts:
    - image: ghcr.io/null-ptr-exception/db-runbooks
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true
manifests:
  rawYaml:
    - .skaffold-rendered/cluster-dbs/*.yaml
deploy:
  kubectl: {}
