apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30091
