apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aqsh-mariadb-manager
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    resourceNames: ["mariadb"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["k8s.mariadb.com"]
    resources: ["mariadbs"]
    verbs: ["get", "list", "watch"]
